[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
meteora_fee_router = "5c7hSgUxDM1NKAr6nTVpcBpLypdeh6RX2paQueS2Z3Lc"

[programs.devnet]
meteora_fee_router = "5c7hSgUxDM1NKAr6nTVpcBpLypdeh6RX2paQueS2Z3Lc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
